package ru.abrosimov.bookshop;

// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import ru.abrosimov.bookshop.dao.CustomerDAO;
import ru.abrosimov.bookshop.dao.impl.CustomerDAOImpl;
import ru.abrosimov.bookshop.models.Customer;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class BookshopApplicationTest {
    private WebDriver driver;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testSearch() {
        driver.get("http://localhost:8080/");

        driver.findElement(By.id("contactChoice1")).click();
        driver.findElement(By.id("line")).click();
        driver.findElement(By.id("line")).sendKeys("эпос");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("Война и Мир"));

        driver.findElement(By.id("contactChoice2")).click();
        driver.findElement(By.id("line")).click();
        driver.findElement(By.id("line")).sendKeys("Война");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Война и Мир\')]")).getText(), is("Война и Мир"));
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Война и Тир\')]")).getText(), is("Война и Тир"));

        driver.findElement(By.id("contactChoice3")).click();
        driver.findElement(By.id("line")).click();
        driver.findElement(By.id("line")).sendKeys("Сиротин");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.cssSelector("span")).getText(), is("За синей дверью"));

        driver.findElement(By.id("contactChoice4")).click();
        driver.findElement(By.id("line")).click();
        driver.findElement(By.id("line")).sendKeys("2021");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Они\')]")).getText(), is("Они"));
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'За синей дверью\')]")).getText(), is("За синей дверью"));
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Война и Тир\')]")).getText(), is("Война и Тир"));
    }

    @Test
    public void testRegistration() {
        driver.get("http://localhost:8080/");
        driver.findElement(By.linkText("Регистрация")).click();
        driver.findElement(By.id("firstName")).sendKeys("Имя");
        driver.findElement(By.id("middleName")).sendKeys("Отчество");
        driver.findElement(By.id("lastName")).sendKeys("Фамилия");
        driver.findElement(By.id("login")).sendKeys("login");
        driver.findElement(By.id("email")).sendKeys("login@ya.ru");
        driver.findElement(By.id("phone")).sendKeys("+79867336187");
        driver.findElement(By.id("address")).sendKeys("Москва");
        driver.findElement(By.id("password")).sendKeys("qwerty");
        driver.findElement(By.cssSelector("input:nth-child(10)")).click();
        driver.findElement(By.linkText("Личный Кабинет")).click();
        {
            String value = driver.findElement(By.id("firstName")).getAttribute("value");
            assertThat(value, is("Имя"));
        }
        {
            String value = driver.findElement(By.id("middleName")).getAttribute("value");
            assertThat(value, is("Отчество"));
        }
        {
            String value = driver.findElement(By.id("lastName")).getAttribute("value");
            assertThat(value, is("Фамилия"));
        }
        {
            String value = driver.findElement(By.id("login")).getAttribute("value");
            assertThat(value, is("login"));
        }
        {
            String value = driver.findElement(By.id("email")).getAttribute("value");
            assertThat(value, is("login@ya.ru"));
        }
        {
            String value = driver.findElement(By.id("phone")).getAttribute("value");
            assertThat(value, is("+79867336187"));
        }
        {
            String value = driver.findElement(By.id("address")).getAttribute("value");
            assertThat(value, is("Москва"));
        }
        {
            String value = driver.findElement(By.id("password")).getAttribute("value");
            assertThat(value, is("qwerty"));
        }
        driver.findElement(By.linkText("Выйти")).click();
    }

    @Test
    public void testBookOrder() {
        driver.get("http://localhost:8080/");
        driver.findElement(By.linkText("Войти")).click();
        driver.findElement(By.id("login")).click();
        driver.findElement(By.id("login")).sendKeys("login");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("qwerty");
        driver.findElement(By.cssSelector("input:nth-child(4)")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Война и Мир\')]")).click();
        driver.findElement(By.id("orders")).click();
        driver.findElement(By.id("orderButton")).click();


        assertThat(driver.findElement(By.cssSelector("span:nth-child(1)")).getText(), is("Война и Мир x 5008.99 = 5008.99;"));
        assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Статус заказа: Открыт."));

        driver.findElement(By.linkText("Выйти")).click();
    }

    @Test
    public void testBookAdd() {
        driver.get("http://localhost:8080/");
        driver.findElement(By.linkText("Войти")).click();
        driver.findElement(By.id("login")).click();
        driver.findElement(By.id("login")).sendKeys("yyatancuyu");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("qws");
        driver.findElement(By.cssSelector("input:nth-child(4)")).click();
        driver.findElement(By.linkText("Добавить Книгу")).click();
        driver.findElement(By.id("name")).click();
        driver.findElement(By.id("name")).sendKeys("Новая Книга");
        driver.findElement(By.id("authors")).click();
        driver.findElement(By.id("authors")).sendKeys("Я");
        driver.findElement(By.id("genre")).click();
        driver.findElement(By.id("genre")).sendKeys("крутость");
        driver.findElement(By.id("publisher")).click();
        driver.findElement(By.id("publisher")).sendKeys("Бук");
        driver.findElement(By.id("yearOfPublication")).click();
        driver.findElement(By.id("yearOfPublication")).sendKeys("2023");
        driver.findElement(By.id("numberOfPages")).click();
        driver.findElement(By.id("numberOfPages")).sendKeys("1");
        driver.findElement(By.id("amount")).click();
        driver.findElement(By.id("amount")).sendKeys("1");
        driver.findElement(By.id("price")).click();
        driver.findElement(By.id("price")).sendKeys("100");
        driver.findElement(By.cssSelector("input:nth-child(11)")).click();

        assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Новая Книга"));
        assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Автор: Я"));

        driver.findElement(By.id("deleteButton")).click();
        driver.findElement(By.linkText("Выйти")).click();
    }

    @Test
    public void testOrderCheckout() throws InterruptedException {
        driver.get("http://localhost:8080/");
        driver.findElement(By.linkText("Войти")).click();
        driver.findElement(By.id("login")).click();
        driver.findElement(By.id("login")).sendKeys("login");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("qwerty");
        driver.findElement(By.cssSelector("input:nth-child(4)")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Они\')]")).click();
        driver.findElement(By.id("orderButton")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Они x 1700.0 = 1700.0;\')]")).click();
        driver.findElement(By.id("orders")).click();
        {
            WebElement dropdown = driver.findElement(By.id("orders"));
            dropdown.findElement(By.xpath("//option[. = 'Заказ №41']")).click();
        }
        driver.findElement(By.id("orderButton")).click();
        driver.findElement(By.cssSelector(".fs-4")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Мы\')]")).click();
        driver.findElement(By.id("orders")).click();
        {
            WebElement dropdown = driver.findElement(By.id("orders"));
            dropdown.findElement(By.xpath("//option[. = 'Заказ №41']")).click();
        }
        driver.findElement(By.id("orderButton")).click();
        driver.findElement(By.cssSelector(".fs-4")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Война и Мир\')]")).click();
        driver.findElement(By.id("orders")).click();
        {
            WebElement dropdown = driver.findElement(By.id("orders"));
            dropdown.findElement(By.xpath("//option[. = 'Заказ №41']")).click();
        }
        driver.findElement(By.id("orderButton")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Война и Мир x 5008.99 = 5008.99;\')]")).click();
        driver.findElement(By.id("orders")).click();
        {
            WebElement dropdown = driver.findElement(By.id("orders"));
            dropdown.findElement(By.xpath("//option[. = 'Заказ №41']")).click();
        }
        driver.findElement(By.id("orderButton")).click();

        // assure order
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Война и Мир x 5008.99 = 10017.98;\')]")).getText(), is("Война и Мир x 5008.99 = 10017.98;"));
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Они x 1700.0 = 3400.0;\')]")).getText(), is("Они x 1700.0 = 3400.0;"));
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Мы x 1700.0 = 1700.0;\')]")).getText(), is("Мы x 1700.0 = 1700.0;"));
        assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Статус заказа: Открыт."));
        assertThat(driver.findElement(By.cssSelector("h1:nth-child(7)")).getText(), is("ИТОГО:15117.98"));
        driver.findElement(By.id("checkoutButton")).click();
        driver.findElement(By.id("datetimeOfDelivery")).click();
        driver.findElement(By.id("datetimeOfDelivery")).sendKeys("2023-04-02");
        {
            String value = driver.findElement(By.id("deliveryAddress")).getAttribute("value");
            assertThat(value, is("Москва"));
        }
        driver.findElement(By.cssSelector("form > input")).click();

        // order is closed
        assertThat(driver.findElement(By.xpath("//span[contains(.,\'Статус заказа: Закрыт.\')]")).getText(), is("Статус заказа: Закрыт."));

        driver.findElement(By.linkText("Выйти")).click();
    }
}
